/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  contributionSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "Getting Started",
      items: [
        {
          type: "autogenerated",
          dirName: "contributing/getting-started",
        },
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "Tutorial - Basics",
      items: [
        {
          type: "autogenerated",
          dirName: "contributing/tutorial-basics",
        },
      ],
    },
  ],
  fundamentalsSidebar: [
    {
      type: "category",
      label: "Fundamentals",
      items: ["fundamentals/tokenization"],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
